<?php
/**
 * Ultimate Flatsome VibeCode - Core HTML Shortcodes Renderer
 *
 * @package UltimateFlatsomeVibeCode
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

function vbc_register_shortcodes() {
    $tags = array(
        'div', 'box', 'block', 'container', 'p', 'i', 'span', 'a', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'li', 'ul', 'ol', 'table', 'tr', 'td', 'th', 'b', 'strong', 'em', 'u',
        'hr', 'br', 'img'
    );

    foreach ($tags as $tag) {
        add_shortcode('vbc_' . $tag, 'vbc_shortcode_renderer');
        add_shortcode('vbc_' . $tag . '_inner', 'vbc_shortcode_renderer');
        for ($i = 1; $i <= 10; $i++) {
            add_shortcode('vbc_' . $tag . '_inner_' . $i, 'vbc_shortcode_renderer');
        }
    }

    // Register vbc_section — wrapper cho Flatsome native elements
    add_shortcode('vbc_section', 'vbc_section_renderer');
}
add_action('init', 'vbc_register_shortcodes');

add_filter('no_texturize_shortcodes', 'vbc_no_texturize_shortcodes');
function vbc_no_texturize_shortcodes($shortcodes) {
    $tags = array(
        'div', 'box', 'block', 'container', 'p', 'i', 'span', 'a', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'li', 'ul', 'ol', 'table', 'tr', 'td', 'th', 'b', 'strong', 'em', 'u',
        'hr', 'br', 'img', 'section', 'tabs', 'tab', 'card', 'testimonial', 'accordion', 'accordion_item', 'button', 'slider', 'slide', 'post'
    );
    foreach ($tags as $tag) {
        $shortcodes[] = 'vbc_' . $tag;
        $shortcodes[] = 'vbc_' . $tag . '_inner';
        for ($i = 1; $i <= 10; $i++) {
            $shortcodes[] = 'vbc_' . $tag . '_inner_' . $i;
        }
    }
    return $shortcodes;
}

/**
 * [vbc_section] — Wrapper bao ngoài các Flatsome native shortcodes.
 * Toàn bộ CSS của section (kể cả CSS của các phần tử con bên trong)
 * được đặt trong thuộc tính custom_css dưới dạng CSS selector rules.
 *
 * Attributes:
 *   id          — ID CSS duy nhất của section (bắt buộc, dùng để scope CSS)
 *   class       — CSS class bổ sung cho wrapper div
 *   custom_css  — CSS rules dạng:
 *                   selector { ... }                   (áp dụng cho wrapper)
 *                   selector .section-title { ... }    (áp dụng cho con)
 *                   @media (max-width:768px) { selector { ... } }
 */
function vbc_section_renderer($atts, $content = null) {
    global $vbc_accumulated_css;
    if (!is_array($vbc_accumulated_css)) $vbc_accumulated_css = array();

    $atts = shortcode_atts(array(
        'id'         => '',
        'class'      => '',
        'custom_css' => '',
    ), $atts, 'vbc_section');

    // Tạo ID duy nhất nếu không được cung cấp
    $section_id = !empty($atts['id']) ? sanitize_html_class($atts['id']) : 'vbc-s-' . substr(md5(uniqid()), 0, 8);

    // Build class list
    $classes = array('vbc-section');
    if (!empty($atts['class'])) {
        $classes[] = esc_attr($atts['class']);
    }
    $class_str = implode(' ', $classes);

    // Xử lý custom_css: thay "selector" bằng "#section_id"
    if (!empty($atts['custom_css'])) {
        $raw_css = $atts['custom_css'];
        $scoped_selector = '#' . $section_id;

        // Thay tất cả "selector" (từ riêng) bằng scoped selector
        $compiled_css = preg_replace('/\bselector\b/', $scoped_selector, $raw_css);

        // Inject vào accumulated CSS pool (in ra ở wp_footer)
        $vbc_accumulated_css['vbc_section_' . $section_id] = $compiled_css;
    }

    // Render nội dung (Flatsome native shortcodes bên trong)
    $inner = !empty($content) ? do_shortcode($content) : '';
    // Remove wpautop artifacts
    $inner = preg_replace('/<p\s*>/', '', $inner);
    $inner = preg_replace('/<\/p>/', '', $inner);
    $inner = preg_replace('/<br\s*\/?>/', '', $inner);

    return '<div id="' . esc_attr($section_id) . '" class="' . esc_attr($class_str) . '">' . $inner . '</div>';
}


/**
 * Helper function to remove plain <p> and <br> tags auto-generated by wpautop and normalize quotes.
 */
function vbc_clean_inner_content($content) {
    if (empty($content)) {
        return '';
    }

    $content = str_replace(array('&#8220;', '&#8221;', '“', '”'), '"', $content);
    $content = str_replace(array('&#8216;', '&#8217;', '‘', '’'), "'", $content);

    // Clean wpautop injected paragraphs and line breaks around shortcodes
    $content = preg_replace('/^<\/p>|^<br\s*\/?>|<p>$/i', '', trim($content));
    $content = preg_replace('/<p>\s*(\[vbc_[^\]]+\])\s*<\/p>/i', '$1', $content);
    $content = preg_replace('/<p>\s*(\[\/vbc_[^\]]+\])\s*<\/p>/i', '$1', $content);

    return $content;
}

function vbc_shortcode_renderer($atts, $content = null, $tag = '') {
    $html_tag = str_replace('vbc_', '', $tag);

    // Loại bỏ suffix lồng nhau như _inner, _inner_1, v.v. để lấy tag HTML gốc
    $html_tag = preg_replace('/_inner(_\d+)?$/', '', $html_tag);

    // Map các alias của div về thẻ div thực tế
    if (in_array($html_tag, array('box', 'block', 'container'))) {
        $html_tag = 'div';
    }

    $defaults = array(
        'content' => '',
        'text' => '',
        'title' => '',
        'class' => '',
        'custom_class' => '',
        'custom_css' => '',
        'custom_attributes' => '',
        'font_family' => '',

        // Dimensions & Box Model
        'width' => '', 'width__md' => '', 'width__sm' => '',
        'height' => '', 'height__md' => '', 'height__sm' => '',
        'max_width' => '', 'max_width__md' => '', 'max_width__sm' => '',
        'min_width' => '', 'min_width__md' => '', 'min_width__sm' => '',
        'max_height' => '', 'max_height__md' => '', 'max_height__sm' => '',
        'min_height' => '', 'min_height__md' => '', 'min_height__sm' => '',
        'margin' => '', 'margin__md' => '', 'margin__sm' => '',
        'padding' => '', 'padding__md' => '', 'padding__sm' => '',
        'display' => '', 'display__md' => '', 'display__sm' => '',
        'overflow' => '', 'overflow__md' => '', 'overflow__sm' => '',

        // Colors & Backgrounds
        'color' => '', 'color__md' => '', 'color__sm' => '',
        'background_color' => '', 'background_color__md' => '', 'background_color__sm' => '',
        'bg_color' => '', 'bg_color__md' => '', 'bg_color__sm' => '',
        'background' => '', 'background__md' => '', 'background__sm' => '',
        'bg_gradient' => '', 'bg_gradient__md' => '', 'bg_gradient__sm' => '',
        'bg_image' => '', 'bg_image__md' => '', 'bg_image__sm' => '',

        // Typography
        'font_size' => '', 'font_size__md' => '', 'font_size__sm' => '',
        'font_weight' => '', 'font_weight__md' => '', 'font_weight__sm' => '',
        'line_height' => '', 'line_height__md' => '', 'line_height__sm' => '',
        'letter_spacing' => '', 'letter_spacing__md' => '', 'letter_spacing__sm' => '',
        'text_align' => '', 'text_align__md' => '', 'text_align__sm' => '',
        'text_transform' => '', 'text_transform__md' => '', 'text_transform__sm' => '',
        'text_decoration' => '', 'text_decoration__md' => '', 'text_decoration__sm' => '',

        // Flexbox & Grid
        'flex_direction' => '', 'flex_direction__md' => '', 'flex_direction__sm' => '',
        'justify_content' => '', 'justify_content__md' => '', 'justify_content__sm' => '',
        'align_items' => '', 'align_items__md' => '', 'align_items__sm' => '',
        'flex_wrap' => '', 'flex_wrap__md' => '', 'flex_wrap__sm' => '',
        'gap' => '', 'gap__md' => '', 'gap__sm' => '',
        'grid_template_columns' => '', 'grid_template_columns__md' => '', 'grid_template_columns__sm' => '',
        'grid_columns' => '', 'grid_columns__md' => '', 'grid_columns__sm' => '',
        'grid_gap' => '', 'grid_gap__md' => '', 'grid_gap__sm' => '',

        // Borders & Shapes
        'border' => '', 'border__md' => '', 'border__sm' => '',
        'border_radius' => '', 'border_radius__md' => '', 'border_radius__sm' => '',
        'border_color' => '', 'border_color__md' => '', 'border_color__sm' => '',
        'border_width' => '', 'border_width__md' => '', 'border_width__sm' => '',
        'border_style' => '', 'border_style__md' => '', 'border_style__sm' => '',
        'box_shadow' => '', 'box_shadow__md' => '', 'box_shadow__sm' => '',

        // Positioning & Effects
        'position' => '', 'position__md' => '', 'position__sm' => '',
        'top' => '', 'top__md' => '', 'top__sm' => '',
        'bottom' => '', 'bottom__md' => '', 'bottom__sm' => '',
        'left' => '', 'left__md' => '', 'left__sm' => '',
        'right' => '', 'right__md' => '', 'right__sm' => '',
        'z_index' => '', 'z_index__md' => '', 'z_index__sm' => '',
        'opacity' => '', 'opacity__md' => '', 'opacity__sm' => '',
        'cursor' => '', 'cursor__md' => '', 'cursor__sm' => '',
        'transition' => '', 'transform' => '',

        // Container-specific Options
        'content_source' => 'default',
        'content_manual' => '',
        'meta_key' => '',
        'acf_key' => '',
        'content_position' => 'replace',

        // a-specific
        'link_source' => 'manual',
        'link_url' => '',
        'link_meta_key' => '',
        'link_acf_key' => '',
        'link_target' => '_self',
        'link_rel' => '',

        // img-specific
        'img_source' => 'default',
        'img_attachment' => '',
        'img_url' => '',
        'img_src' => '',
        'src' => '',
        'url' => '',
        'img_meta_key' => '',
        'img_acf_key' => '',
        'alt' => '',

        // Cell-specific
        'colspan' => '',
        'rowspan' => '',

        // ol-specific
        'ol_type' => '1',
        'ol_start' => '',
    );

    $atts = shortcode_atts($defaults, $atts, $tag);

    foreach ($atts as $k => $v) {
        if (is_string($v)) {
            $atts[$k] = str_replace(array('&#8220;', '&#8221;', '“', '”'), '"', $v);
            $atts[$k] = str_replace(array('&#8216;', '&#8217;', '‘', '’'), "'", $atts[$k]);
        }
    }

    if (empty($atts['custom_class']) && !empty($atts['class'])) {
        $atts['custom_class'] = $atts['class'];
    }

    // Biên dịch CSS (desktop → inline style="", responsive → accumulated <style>)
    $compiled = vbc_compile_element_css($atts, 'vbc-css');
    $class_attr   = trim($atts['custom_class'] . ' ' . $compiled['class']);
    $inline_style = $compiled['inline_style'];

    $class_attr_str  = !empty($class_attr)  ? ' class="'  . esc_attr($class_attr)  . '"' : '';
    $style_attr_str  = !empty($inline_style) ? ' style="'  . esc_attr($inline_style) . '"' : '';
    $custom_attrs    = !empty($atts['custom_attributes']) ? ' ' . trim($atts['custom_attributes']) : '';

    // 3. Render các thẻ self-closing (void)
    $void_tags = array('hr', 'br', 'img');
    if (in_array($html_tag, $void_tags)) {
        if ($html_tag === 'br') {
            return '<br>';
        }
        if ($html_tag === 'hr') {
            return '<hr' . $class_attr_str . $style_attr_str . $custom_attrs . '>';
        }
        if ($html_tag === 'img') {
            $img_url = '';
            $img_id = 0;

            if (!empty($atts['src'])) {
                $img_url = $atts['src'];
            } elseif (!empty($atts['img_url'])) {
                $img_url = $atts['img_url'];
            } elseif (!empty($atts['img_src'])) {
                $img_url = $atts['img_src'];
            } elseif (!empty($atts['url'])) {
                $img_url = $atts['url'];
            } elseif ($atts['img_source'] === 'default' && !empty($atts['img_attachment'])) {
                $img_id = intval($atts['img_attachment']);
                if ($img_id > 0) {
                    $img_url = wp_get_attachment_image_url($img_id, 'full');
                }
            } elseif ($atts['img_source'] === 'manual' && !empty($atts['img_url'])) {
                $img_url = $atts['img_url'];
            }
            
            if ($atts['img_source'] === 'post_meta') {
                $meta_key = $atts['img_meta_key'];
                if (!empty($meta_key)) {
                    $val = get_post_meta(get_the_ID(), $meta_key, true);
                    if (is_numeric($val)) {
                        $img_id = intval($val);
                        $img_url = wp_get_attachment_image_url($img_id, 'full');
                    } else {
                        $img_url = $val;
                    }
                }
            } elseif ($atts['img_source'] === 'acf') {
                $acf_key = $atts['img_acf_key'];
                if (!empty($acf_key)) {
                    if (function_exists('get_field')) {
                        $val = get_field($acf_key);
                        if (is_array($val) && isset($val['url'])) {
                            $img_url = $val['url'];
                            if (isset($val['id'])) {
                                $img_id = intval($val['id']);
                            }
                        } elseif (is_numeric($val)) {
                            $img_id = intval($val);
                            $img_url = wp_get_attachment_image_url($img_id, 'full');
                        } else {
                            $img_url = $val;
                        }
                    } else {
                        $val = get_post_meta(get_the_ID(), $acf_key, true);
                        if (is_numeric($val)) {
                            $img_id = intval($val);
                            $img_url = wp_get_attachment_image_url($img_id, 'full');
                        } else {
                            $img_url = $val;
                        }
                    }
                }
            }
            
            $img_url = esc_url($img_url);
            $alt = esc_attr($atts['alt']);
            if (empty($alt) && $img_id > 0) {
                $alt = esc_attr(get_post_meta($img_id, '_wp_attachment_image_alt', true));
            }
            
            if (empty($img_url)) {
                if (is_user_logged_in() && (is_admin() || is_customize_preview() || isset($_GET['uxb_iframe']))) {
                    return '<div style="background:#f3f3f3;padding:15px;text-align:center;border:1px dashed #ccc;font-size:11px;"' . $class_attr_str . $custom_attrs . '>VBC Image (No Source Selected)</div>';
                }
                return '';
            }

            return '<img src="' . $img_url . '" alt="' . $alt . '"' . $class_attr_str . $style_attr_str . $custom_attrs . '>';
        }
    }

    // 4. Render các thẻ Container
    // Xử lý dữ liệu động
    $dynamic_content = '';
    $current_post_id = get_the_ID();
    if (!$current_post_id && isset($_GET['post'])) {
        $current_post_id = intval($_GET['post']);
    }
    if (!$current_post_id && isset($GLOBALS['post']->ID)) {
        $current_post_id = $GLOBALS['post']->ID;
    }

    if ($atts['content_source'] === 'post_title' || $atts['content_source'] === 'title') {
        $dynamic_content = get_the_title($current_post_id);
    } elseif ($atts['content_source'] === 'post_excerpt' || $atts['content_source'] === 'excerpt') {
        $dynamic_content = get_the_excerpt($current_post_id);
    } elseif ($atts['content_source'] === 'post_date' || $atts['content_source'] === 'date') {
        $dynamic_content = get_the_date('', $current_post_id);
    } elseif ($atts['content_source'] === 'post_author' || $atts['content_source'] === 'author') {
        $dynamic_content = get_the_author();
    } elseif ($atts['content_source'] === 'manual') {
        $dynamic_content = $atts['content_manual'];
    } elseif ($atts['content_source'] === 'post_meta') {
        $meta_key = trim($atts['meta_key']);
        if (!empty($meta_key)) {
            $meta_key_lower = strtolower($meta_key);
            if ($meta_key_lower === 'post_title' || $meta_key_lower === 'title') {
                $dynamic_content = get_the_title($current_post_id);
            } elseif ($meta_key_lower === 'post_excerpt' || $meta_key_lower === 'excerpt') {
                $dynamic_content = get_the_excerpt($current_post_id);
            } elseif ($meta_key_lower === 'post_date' || $meta_key_lower === 'date') {
                $dynamic_content = get_the_date('', $current_post_id);
            } elseif ($meta_key_lower === 'post_author' || $meta_key_lower === 'author') {
                $dynamic_content = get_the_author();
            } elseif ($meta_key_lower === 'post_url' || $meta_key_lower === 'permalink') {
                $dynamic_content = get_permalink($current_post_id);
            } elseif ($meta_key_lower === 'id' || $meta_key_lower === 'post_id') {
                $dynamic_content = $current_post_id;
            } else {
                $dynamic_content = get_post_meta($current_post_id, $meta_key, true);
                if (($dynamic_content === '' || $dynamic_content === false || $dynamic_content === null) && $current_post_id > 0) {
                    $p_obj = get_post($current_post_id);
                    if ($p_obj && isset($p_obj->$meta_key)) {
                        $dynamic_content = $p_obj->$meta_key;
                    }
                }
            }
        }
    } elseif ($atts['content_source'] === 'acf') {
        $acf_key = trim($atts['acf_key']);
        if (!empty($acf_key)) {
            if (function_exists('get_field')) {
                $dynamic_content = get_field($acf_key, $current_post_id);
            } else {
                $dynamic_content = get_post_meta($current_post_id, $acf_key, true);
            }
        }
    }

    if (is_array($dynamic_content) || is_object($dynamic_content)) {
        $dynamic_content = json_encode($dynamic_content);
    } else {
        $dynamic_content = strval($dynamic_content);
    }

    $inner_content_to_render = !empty($atts['content']) ? $atts['content'] : (!empty($atts['text']) ? $atts['text'] : (!empty($atts['title']) && in_array($html_tag, array('h1','h2','h3','h4','h5','h6','a','span','p','b','strong')) ? $atts['title'] : $content));
    $inner_content_to_render = vbc_clean_inner_content($inner_content_to_render);

    // Tự động thay thế placeholders động nếu có: {{post_title}}, {{title}}, {{post_excerpt}}, {{date}}, {{permalink}}, {{meta:key}}, {{acf:key}}
    if (!empty($inner_content_to_render) && strpos($inner_content_to_render, '{{') !== false) {
        $inner_content_to_render = preg_replace_callback('/\{\{([a-zA-Z0-9_\-:]+)\}\}/', function($matches) use ($current_post_id) {
            $tag = strtolower(trim($matches[1]));
            if ($tag === 'post_title' || $tag === 'title') {
                return get_the_title($current_post_id);
            }
            if ($tag === 'post_excerpt' || $tag === 'excerpt') {
                return get_the_excerpt($current_post_id);
            }
            if ($tag === 'post_date' || $tag === 'date') {
                return get_the_date('', $current_post_id);
            }
            if ($tag === 'post_author' || $tag === 'author') {
                return get_the_author();
            }
            if ($tag === 'post_url' || $tag === 'permalink') {
                return get_permalink($current_post_id);
            }
            if (strpos($tag, 'meta:') === 0) {
                $meta_key = substr($tag, 5);
                return get_post_meta($current_post_id, $meta_key, true);
            }
            if (strpos($tag, 'acf:') === 0) {
                $acf_key = substr($tag, 4);
                if (function_exists('get_field')) {
                    $val = get_field($acf_key, $current_post_id);
                    return is_array($val) ? json_encode($val) : strval($val);
                }
                return get_post_meta($current_post_id, $acf_key, true);
            }
            return $matches[0];
        }, $inner_content_to_render);
    }

    $children = do_shortcode($inner_content_to_render);
    if (strpos($children, '[vbc_') !== false) {
        $children = do_shortcode($children);
    }

    if ($html_tag === 'div') {
        $children = preg_replace('/<p>\s*<\/p>/i', '', $children);
        $children = preg_replace('/<p>\s*(<(?:div|section|article|aside|header|footer|nav|h[1-6]|ul|ol|table)\b)/i', '$1', $children);
        $children = preg_replace('/(<\/(?:div|section|article|aside|header|footer|nav|h[1-6]|ul|ol|table)>)\s*<\/p>/i', '$1', $children);
        $children = preg_replace('/<p>\s*$/i', '', $children);
    }

    if ($atts['content_source'] === 'default') {
        $final_content = $children;
    } else {
        if ($atts['content_position'] === 'replace') {
            $final_content = $dynamic_content;
        } elseif ($atts['content_position'] === 'before') {
            $final_content = $dynamic_content . $children;
        } else {
            $final_content = $children . $dynamic_content;
        }
    }

    // Xử lý các thuộc tính HTML riêng biệt
    $tag_attrs = '';
    if ($html_tag === 'a') {
        $link_url = '';
        if ($atts['link_source'] === 'manual') {
            $link_url = $atts['link_url'];
        } elseif ($atts['link_source'] === 'post_meta') {
            $meta_key = $atts['link_meta_key'];
            if (!empty($meta_key)) {
                $link_url = get_post_meta(get_the_ID(), $meta_key, true);
            }
        } elseif ($atts['link_source'] === 'acf') {
            $acf_key = $atts['link_acf_key'];
            if (!empty($acf_key)) {
                if (function_exists('get_field')) {
                    $acf_value = get_field($acf_key);
                    if (is_array($acf_value) && isset($acf_value['url'])) {
                        $link_url = $acf_value['url'];
                    } else {
                        $link_url = $acf_value;
                    }
                } else {
                    $link_url = get_post_meta(get_the_ID(), $acf_key, true);
                }
            }
        }
        $link_url = esc_url($link_url);
        if (!empty($link_url)) {
            $tag_attrs .= ' href="' . $link_url . '"';
        }
        if (!empty($atts['link_target'])) {
            $tag_attrs .= ' target="' . esc_attr($atts['link_target']) . '"';
        }
        if (!empty($atts['link_rel'])) {
            $tag_attrs .= ' rel="' . esc_attr($atts['link_rel']) . '"';
        }
    } elseif ($html_tag === 'td' || $html_tag === 'th') {
        $colspan = intval($atts['colspan']);
        $rowspan = intval($atts['rowspan']);
        if ($colspan > 0) {
            $tag_attrs .= ' colspan="' . $colspan . '"';
        }
        if ($rowspan > 0) {
            $tag_attrs .= ' rowspan="' . $rowspan . '"';
        }
    } elseif ($html_tag === 'ol') {
        if (!empty($atts['ol_type'])) {
            $tag_attrs .= ' type="' . esc_attr($atts['ol_type']) . '"';
        }
        $ol_start = intval($atts['ol_start']);
        if ($ol_start > 0) {
            $tag_attrs .= ' start="' . $ol_start . '"';
        }
    }

    // Font handling is already done by vbc_compile_element_css()

    // Strip automatic <p> and <br> generated by wpautop on inline/text tags to prevent styling issues (like nested <p> inside headings)
    $text_like_tags = array(
        'span', 'i', 'b', 'strong', 'em', 'u', 'a', 
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 
        'p', 'li', 'button', 'td', 'th'
    );
    if (in_array($html_tag, $text_like_tags)) {
        $final_content = preg_replace('/<\/?p[^>]*>/i', '', $final_content);
        $final_content = preg_replace('/<\/?div[^>]*>/i', '', $final_content);
        $final_content = preg_replace('/^(<br\s*\/?>\s*)+|(<br\s*\/?>\s*)+$/i', '', $final_content);
    }

    // Desktop CSS applied via style="" attribute — always works in UX Builder, frontend, AJAX
    return '<' . $html_tag . $class_attr_str . $style_attr_str . $tag_attrs . $custom_attrs . '>' . $final_content . '</' . $html_tag . '>';
}


/**
 * 2.5 VIBECODE ADVANCED COMPONENT SHORTCODES
 */
add_action('init', 'vbc_register_component_shortcodes');
